-- CreateEnum
CREATE TYPE "ArticleStatus" AS ENUM ('DRAFTING', 'TITLE_READY', 'CONTENT_READY', 'SLUG_DONE', 'KEYWORDS_DONE', 'CATEGORIZED', 'READY_TO_PUBLISH', 'PUBLISHED');

-- AlterEnum
ALTER TYPE "TopicStatus" ADD VALUE 'READY';
